name: adaptifit
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  device_preview: ^1.3.1
  flutter:
    sdk: flutter
  http: ^1.1.0
  table_calendar: ^3.0.9
  intl: ^0.20.2
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: "^2.4.0"
  build_runner: ^2.4.10
  riverpod_generator: ^2.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

# Add these lines at the end of the file

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/adaptifit_icon.jpeg"

flutter_native_splash:
  color: "0xFF1DB954"
  image: assets/images/adaptifit_icon.jpeg
  android: true
  ios: true
